- id: paints
  items:
    - name: Yellow Paint
      price: $1.50
    - name: Blue Paint
      price: $1.50
    - name: Red Paint
      price: $1.50
- id: boxes
  items:
    - name: Cardboard Box
      price: $0.50
    - name: Wooden Box
      price: $1.50
    - name: NASA Grade Special Box
      price: $All of it
- id: moboxes
  items:
    - name:
      price: